language: generic
before_install:
  - sudo apt-get -qq update

install:
  - wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip -O ./packer.zip
  - unzip ./packer.zip
  - ./packer --version

after_success:
  - ./packer validate ./development-environment-base.json
