env:
  - ATLAS_TOKEN=dummytoken

language: generic

install:
  - wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip -O ./packer.zip
  - unzip ./packer.zip
  - ./packer --version

after_success:
  - ./packer validate ./development-environment-base.json
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./packer build ./development-environment-base.json; fi'
