env:
  - ATLAS_TOKEN=dummytoken

language: generic
before_install:
  - sudo apt-get -qq update

install:
  - wget https://releases.hashicorp.com/packer/1.3.0/packer_1.3.0_linux_amd64.zip -O ./packer.zip
  - unzip ./packer.zip
  - ./packer --version

after_success:
  - ./packer validate ./development-environment-base.json
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./packer build ./development-environment-base.json; fi'
