language: generic
before_install:
  - sudo apt-get -qq update

install:
  - wget https://github.com/hashicorp/packer/archive/v1.2.2.zip -O ./packer.zip
  - unzip ./packer.zip
  - ./packer --version

after_success:
  - ./packer validate ./development-environment-base.json
