platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops

inputs:
- name: pipeline
- name: snapshot-metadata

run:
  path: pipeline/tasks/dependency-versions/task

params:
  CONCOURSE_URL: 
  CONCOURSE_TEAM: 
  CONCOURSE_USERNAME: 
  CONCOURSE_PASSWORD: 
  CONCOURSE_PIPELINE:
  SNAPSHOT_VERSIONS_FILE:
  
outputs:
- name: updated-dependency-versions
