---
  - name: Download go archive
    get_url:
      url: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
      dest: /tmp/
      checksum: "sha256:{{go_sha256_checksum}}"

  - name: Unarchive and move go binaries
    unarchive:
      src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
      dest: /usr/local/

  - name: Create symlink to gobin
    file:
      src: /usr/local/go/bin/go
      dest: /usr/bin/go
      state: link
      force: true

  - name: Remove binary
    file:
      path=/tmp/go{{ go_version }}.linux-amd64.tar.gz
      state=absent
