---
  - name: Add repository
    lineinfile:
      line="deb http://apt.newrelic.com/debian/ newrelic non-free"
      dest=/etc/apt/sources.list.d/newrelic.list
      insertbefore=BOF
      state=present
      create=yes

  - name: Add apt key
    apt_key:
      url="https://download.newrelic.com/548C16BF.gpg"
      state=present

  - name: Install newrelic-sysmond
    apt:
      name=newrelic-sysmond
      state=present
      update_cache=yes
