---
  - name: update
    apt:
      upgrade=dist
      autoremove=yes
      update_cache=yes

  - name: install packages
    apt:
      name={{ item }}
      state=present
      autoremove=yes
    with_items:
      - putty-tools
      - dos2unix
      - wmctrl
      - byzanz
      - alien
      - tree
      - jq
      - xmlstarlet
      - multitail
      - ldap-utils
      - openjdk-8-jdk
      - openjdk-8-source
      - ant
      - gnome-terminal
      - ngrep
      - nmap
      - sslscan
      - dnsutils
      - graphviz
      - zram-config
      - xdg-utils
      - chromium-browser
      - unzip
      - gnome-system-monitor
      - baobab
      - wkhtmltopdf
      - bash-completion
      - autojump
      - nano
