---
  - name: "install vscode"
    apt:
      deb: "https://vscode-update.azurewebsites.net/{{ vscode_version }}/linux-deb-x64/stable"
      autoremove: yes

  - name: install vscode extensions
    shell: "code --install-extension {{ item }}"
    become: true
    become_user: vagrant
    with_items:
      - ms-python.python
      - rogalmic.bash-debug
      - donjayamanne.githistory
      - formulahendry.auto-close-tag
      - humao.rest-client
      - redhat.vscode-yaml
      - haaaad.ansible
