---
- hosts: all
  vars:
    cf_cli_version: "6.30.0"
    maven_version: "3.5.0"
    maven_checksum: "35c39251d2af99b6624d40d801f6ff02"
    intellij_version: "2017.2.3"
    sts_version: "3.9.0"
    eclipse_version: "4.7.0"
    docker_compose_version: "1.16.1"
    atom_version: "1.19.7"
    gradle_version: "4.1"
    go_version: "1.9"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.31"
    bosh_cli_sha1_checksum: "b41f555b87b9898d501a29c995dc5eb8563d4308"
    yaml_linux_version: "1.11"
    terraform_version: "0.10.4"
    bosh_bootloader_version: "4.5.1"
    postman_version: "5.2.0"
    postman_sha1_checksum: "8973ABB64572A45E8FBD63D369DE1A402796D4E5"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - git
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
