---
- hosts: all
  vars:
    cf_cli_version: "6.31.0"
    maven_version: "3.5.0"
    maven_checksum: "35c39251d2af99b6624d40d801f6ff02"
    intellij_version: "2017.2.4"
    sts_version: "3.9.0"
    eclipse_version: "4.7.0"
    docker_compose_version: "1.16.1"
    atom_version: "1.20.1"
    gradle_version: "4.2"
    go_version: "1.9"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.40"
    bosh_cli_sha1_checksum: "0045668aa6582ddd518cfb2b6134eba439bbb94d"
    yaml_linux_version: "1.11"
    terraform_version: "0.10.5"
    bosh_bootloader_version: "4.8.0"
    postman_version: "5.2.0"
    postman_sha1_checksum: "8973ABB64572A45E8FBD63D369DE1A402796D4E5"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - git
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
