---
- hosts: all
  vars:
    cf_cli_version: "6.26.0"
    maven_version: "3.5.0"
    maven_checksum: "35c39251d2af99b6624d40d801f6ff02"
    sbt_version: "0.13.13"
    intellij_version: "2017.1.1"
    intellij_sha256_checksum: "3b7f2b906c2a22b3323aba1f9bd4719147f0534e823d4313265c6bcbf92cda60"
    sts_version: "3.8.4"
    eclipse_version: "4.6.3"
    docker_compose_version: "1.12.0"
    atom_version: "1.15.0"
    gradle_version: "3.5"
    go_version: "1.8.1"
    go_sha256_checksum: "a579ab19d5237e263254f1eac5352efcf1d70b9dacadb6d6bb12b0911ede8994"
    compliance_masonry_version: "1.1.2"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - sbt
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
