---
- hosts: all
  vars:
    cf_cli_version: "6.33.1"
    maven_version: "3.5.0"
    intellij_version: "2017.3.2"
    sts_version: "3.9.1"
    eclipse_version: "4.7.1a"
    docker_compose_version: "1.18.0"
    atom_version: "1.20.1"
    gradle_version: "4.4.1"
    go_version: "1.9.2"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.45"
    yaml_linux_version: "1.14.0"
    terraform_version: "0.11.1"
    bosh_bootloader_version: "5.11.0"
    postman_version: "5.3.2"
    fly_version: "3.8.0"
    groovy_version: "2.4.13"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - git
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
    - fly
    - groovy
