---
- hosts: all
  vars:
    cf_cli_version: "6.39.1"
    maven_version: "3.5.4"
    sts_version: "3.9.6"
    eclipse_version: "4.9.0"
    docker_compose_version: "1.22.0"
    atom_version: "1.26.1"
    gradle_version: "4.10.2"
    go_version: "1.11"
    compliance_masonry_version: "1.1.5"
    bosh_cli_version: "5.2.2"
    yq_linux_version: "1.14.0"
    terraform_version: "0.11.8"
    bosh_bootloader_version: "6.9.16"
    credhub_cli_version: "1.7.7"
    postman_version: "6.3.0"
    fly_version: "3.14.1"
    groovy_version: "2.4.15"
    vscode_version: "1.23.0"
    hub_version: "2.5.1"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - git
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
    - fly
    - credhub
    - groovy
    - taurus
    - json2yaml
    - vscode
    - hub
