---
- hosts: all
  vars:
    cf_cli_version: "6.29.2"
    maven_version: "3.5.0"
    maven_checksum: "35c39251d2af99b6624d40d801f6ff02"
    intellij_version: "2017.2.2"
    sts_version: "3.9.0"
    eclipse_version: "4.7.0"
    docker_compose_version: "1.15.0"
    atom_version: "1.19.4"
    gradle_version: "4.0.2"
    go_version: "1.8.3"
    compliance_masonry_version: "1.1.2"
    bosh_cli_version: "2.0.28"
    bosh_cli_sha1_checksum: "7b7629fcdf8839cf29bf25d97e8ea6beb3b9a7b2"
    yaml_linux_version: "1.11"
    terraform_version: "0.10.2"
    bosh_bootloader_version: "4.1.4"
    postman_version: "5.1.3"
    postman_sha1_checksum: "7010D79F3D088FB1F5157ED639515C273BA78BDC"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - git
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
    - postman
    - gitbook
    - compliance_masonry
    - gcloud
    - newrelic
    - bosh
