---
- hosts: all
  vars:
    cf_cli_version: "6.25.0"
    maven_version: "3.3.9"
    maven_checksum: "516923b3955b6035ba6b0a5b031fbd8b"
    sbt_version: "0.13.13"
    intellij_version: "2016.3.5"
    sts_version: "3.8.3"
    eclipse_version: "4.6.2"
    docker_compose_version: "1.11.2"
    atom_version: "1.15.0"
    gradle_version: "3.4.1"
    go_version: "1.8"
  gather_facts: yes
  become: yes
  roles:
    - disable_auto_update
    - developer_packages
    - atom
    - docker_service
    - docker_compose
    - cf_cli
    - maven
    - sbt
    - gradle
    - intellij
    - sts
    - unity_desktop
    - go
