---
  - name: install packages
    apt:
      name: "{{ packages }}"
      autoremove: yes
    vars:
      packages:
      - openjdk-8-jre-headless
      - java-common
      - python-tk
      - python-dev
      - libxml2-dev
      - libxslt-dev
      - zlib1g-dev

  - name: install taurus
    pip:
      name: bzt
